export const formulaSettingsSeed = [
  {
    setting_key: "listing.lot_net_selling_price",
    category: "Listing Pricing",
    label: "Lot Net Selling Price",
    formula_text: "Lot Area x Price per sqm = Net Selling Price",
    description: "Used for lot-only listings with area-based pricing.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 10,
  },
  {
    setting_key: "listing.package_net_selling_price",
    category: "Listing Pricing",
    label: "Package Net Selling Price",
    formula_text: "Package Price = Net Selling Price",
    description: "Used for house-and-lot package pricing.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 20,
  },
  {
    setting_key: "listing.manual_net_selling_price",
    category: "Listing Pricing",
    label: "Manual Net Selling Price",
    formula_text: "Admin Input = Net Selling Price",
    description: "Used when admin directly inputs the final listing price.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 30,
  },
  {
    setting_key: "listing.default_lmf_rate",
    category: "Listing Pricing",
    label: "Legal Miscellaneous Fee",
    formula_text: "Net Selling Price x LMF Rate = Legal Miscellaneous Fee",
    description: "Default rate used when creating listings.",
    value_type: "percentage",
    setting_value: "10",
    default_value: "10",
    is_editable: true,
    sort_order: 40,
  },
  {
    setting_key: "listing.total_contract_price",
    category: "Listing Pricing",
    label: "Total Contract Price",
    formula_text: "Net Selling Price + Legal Miscellaneous Fee = Total Contract Price",
    description: "Main amount used by payments, SOA, commissions, and reports.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 50,
  },
  {
    setting_key: "reservation.default_reservation_fee",
    category: "Reservation and Buyer Account",
    label: "Reservation Balance",
    formula_text: "Total Contract Price - Reservation Fee = Remaining Balance",
    description: "Used as a default reservation fee, but each listing/account can still have its own value.",
    value_type: "currency",
    setting_value: "50000",
    default_value: "50000",
    is_editable: true,
    sort_order: 60,
  },
  {
    setting_key: "reservation.default_downpayment_rate",
    category: "Reservation and Buyer Account",
    label: "Downpayment Amount",
    formula_text: "Total Contract Price x Downpayment Rate = Downpayment Amount",
    description: "Used when downpayment terms are selected.",
    value_type: "percentage",
    setting_value: "30",
    default_value: "30",
    is_editable: true,
    sort_order: 70,
  },
  {
    setting_key: "reservation.spot_downpayment_balance",
    category: "Reservation and Buyer Account",
    label: "Spot Downpayment Balance",
    formula_text: "Downpayment Amount - Reservation Fee = Spot Downpayment",
    description: "Shows how much remains after reservation fee is deducted from downpayment.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 80,
  },
  {
    setting_key: "reservation.installment_principal_balance",
    category: "Reservation and Buyer Account",
    label: "Installment Principal Balance",
    formula_text: "Total Contract Price - Reservation Fee - Downpayment Paid = Installment Principal Balance",
    description: "Base amount for installment schedule.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 90,
  },
  {
    setting_key: "payment.allowed_term_months",
    category: "Payment Schedule / SOA",
    label: "Monthly Amortization",
    formula_text: "Installment Principal Balance / Term Months = Monthly Amortization",
    description: "Monthly amortization is locked after account creation unless admin restructures the account.",
    value_type: "json",
    setting_value: "[36,60]",
    default_value: "[36,60]",
    is_editable: true,
    sort_order: 100,
  },
  {
    setting_key: "payment.default_offset_policy",
    category: "Payment Schedule / SOA",
    label: "Advance Payment Allocation",
    formula_text: "Excess Payment / Monthly Amortization = Number of Future Months Paid",
    description: "Extra payment applies to future dues and shortens duration. It must not reduce monthly amortization.",
    value_type: "text",
    setting_value: "apply_to_next_unpaid_due",
    default_value: "apply_to_next_unpaid_due",
    is_editable: true,
    sort_order: 110,
  },
  {
    setting_key: "payment.default_balloon_policy",
    category: "Payment Schedule / SOA",
    label: "Balloon Payment Allocation",
    formula_text: "Balloon Payment / Monthly Amortization = Number of Future Months Paid Ahead",
    description: "Balloon payment reduces duration. It must not lower monthly amount.",
    value_type: "text",
    setting_value: "reduce_duration",
    default_value: "reduce_duration",
    is_editable: true,
    sort_order: 120,
  },
  {
    setting_key: "payment.running_balance",
    category: "Payment Schedule / SOA",
    label: "Running Balance",
    formula_text: "Previous Running Balance - Verified Payment Applied = New Running Balance",
    description: "Used in SOA after verified payment allocation.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 130,
  },
  {
    setting_key: "payment.paid_ahead_status",
    category: "Payment Schedule / SOA",
    label: "Paid Ahead Status",
    formula_text: "If future due row is fully paid before due date, status = Paid Ahead",
    description: "Used when excess payment covers future rows.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 140,
  },
  {
    setting_key: "penalty.grace_period_days",
    category: "Penalty",
    label: "Grace Period",
    formula_text: "Due Date + Grace Period Days = Penalty Start Date",
    description: "Number of days after due date before penalty applies.",
    value_type: "days",
    setting_value: "5",
    default_value: "5",
    is_editable: true,
    sort_order: 150,
  },
  {
    setting_key: "penalty.monthly_penalty_rate",
    category: "Penalty",
    label: "Monthly Penalty",
    formula_text: "Overdue Balance x Penalty Rate = Penalty Amount",
    description: "Penalty rate for past due schedules.",
    value_type: "percentage",
    setting_value: "3",
    default_value: "3",
    is_editable: true,
    sort_order: 160,
  },
  {
    setting_key: "penalty.past_due_status",
    category: "Penalty",
    label: "Past Due Status",
    formula_text: "If Due Date + Grace Period Days < Today and Balance > 0, account/schedule = Past Due",
    description: "Marks unpaid overdue schedules as past due.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 170,
  },
  {
    setting_key: "reference.cash_prefix",
    category: "Cash Reference Number",
    label: "Cash Reference Format",
    formula_text: "CASH-YYYYMMDD-CU0000-0001",
    description: "Cash payments auto-generate a reference number after saving.",
    value_type: "text",
    setting_value: "CASH",
    default_value: "CASH",
    is_editable: true,
    sort_order: 180,
  },
  {
    setting_key: "reference.cash_sequence",
    category: "Cash Reference Number",
    label: "Cash Reference Sequence",
    formula_text: "Daily running number per client unit",
    description: "Sequence must avoid duplicates.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 190,
  },
  {
    setting_key: "seller_group.allowed_pool_rate_range",
    category: "Seller Groups and Commission",
    label: "Seller Group Pool Rate",
    formula_text: "Seller Group Pool Rate = Selected Group Rate",
    description: "Pool rate is controlled by seller group. Sellers can view only. Admin edits only.",
    value_type: "json",
    setting_value: "[6,7,8,9,10,11,12,13,14,15]",
    default_value: "[6,7,8,9,10,11,12,13,14,15]",
    is_editable: true,
    sort_order: 200,
  },
  {
    setting_key: "commission.base",
    category: "Seller Groups and Commission",
    label: "Commission Base",
    formula_text: "Commission Base = Snapshot Total Contract Price",
    description: "Commission must use account snapshot, not edited listing price.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 210,
  },
  {
    setting_key: "commission.gross_commission",
    category: "Seller Groups and Commission",
    label: "Gross Commission",
    formula_text: "Commission Base x Snapshot Commission Rate = Gross Commission",
    description: "Rate must come from seller group/account snapshot.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 220,
  },
  {
    setting_key: "commission.default_group_pool_rate",
    category: "Seller Groups and Commission",
    label: "Group Commission Pool",
    formula_text: "Commission Base x Group Pool Rate = Total Group Commission Pool",
    description: "Default group pool rate used when creating a seller group.",
    value_type: "percentage",
    setting_value: "10",
    default_value: "10",
    is_editable: true,
    sort_order: 230,
  },
  {
    setting_key: "commission.release_milestone_1",
    category: "Commission Release",
    label: "First Release",
    formula_text: "Gross Commission x 20% = First Release Amount",
    description: null,
    value_type: "percentage",
    setting_value: "20",
    default_value: "20",
    is_editable: true,
    sort_order: 240,
  },
  {
    setting_key: "commission.release_milestone_2",
    category: "Commission Release",
    label: "Second Release",
    formula_text: "Gross Commission x 40% = Cumulative Released Target",
    description: null,
    value_type: "percentage",
    setting_value: "40",
    default_value: "40",
    is_editable: true,
    sort_order: 250,
  },
  {
    setting_key: "commission.release_milestone_3",
    category: "Commission Release",
    label: "Third Release",
    formula_text: "Gross Commission x 60% = Cumulative Released Target",
    description: null,
    value_type: "percentage",
    setting_value: "60",
    default_value: "60",
    is_editable: true,
    sort_order: 260,
  },
  {
    setting_key: "commission.release_milestone_4",
    category: "Commission Release",
    label: "Fourth Release",
    formula_text: "Gross Commission x 75% = Cumulative Released Target",
    description: null,
    value_type: "percentage",
    setting_value: "75",
    default_value: "75",
    is_editable: true,
    sort_order: 270,
  },
  {
    setting_key: "commission.retention_rate",
    category: "Commission Release",
    label: "Retention",
    formula_text: "Gross Commission x 25% = Retention Amount",
    description: null,
    value_type: "percentage",
    setting_value: "25",
    default_value: "25",
    is_editable: true,
    sort_order: 280,
  },
  {
    setting_key: "commission.release_net_amount",
    category: "Commission Release",
    label: "Release Net Amount",
    formula_text: "Gross Release Amount - Cash Advance Deduction = Net Release Amount",
    description: "Used when releasing commissions with cash advance deduction.",
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 290,
  },
  {
    setting_key: "cash_advance.balance",
    category: "Cash Advance Deduction",
    label: "Cash Advance Balance",
    formula_text: "Approved Cash Advance - Total Deductions = Remaining Cash Advance Balance",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 300,
  },
  {
    setting_key: "cash_advance.default_deduction_policy",
    category: "Cash Advance Deduction",
    label: "Cash Advance Deduction",
    formula_text: "Minimum of Release Amount and Remaining Cash Advance Balance = Deduction Amount",
    description: null,
    value_type: "text",
    setting_value: "deduct_from_next_release",
    default_value: "deduct_from_next_release",
    is_editable: true,
    sort_order: 310,
  },
  {
    setting_key: "voucher.prefix",
    category: "Voucher Numbering",
    label: "Voucher Number Format",
    formula_text: "VCH-YYYYMMDD-0001",
    description: null,
    value_type: "text",
    setting_value: "VCH",
    default_value: "VCH",
    is_editable: true,
    sort_order: 320,
  },
  {
    setting_key: "voucher.commission_amount",
    category: "Voucher Numbering",
    label: "Commission Voucher Amount",
    formula_text: "Commission Release Net Amount = Voucher Amount",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 330,
  },
  {
    setting_key: "voucher.cash_advance_amount",
    category: "Voucher Numbering",
    label: "Cash Advance Voucher Amount",
    formula_text: "Approved Cash Advance Amount = Voucher Amount",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 340,
  },
  {
    setting_key: "voucher.refund_amount",
    category: "Voucher Numbering",
    label: "Refund Voucher Amount",
    formula_text: "Refund Amount = Voucher Amount",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 350,
  },
  {
    setting_key: "cancellation.settlement",
    category: "Cancellation / Refund",
    label: "Cancellation Settlement",
    formula_text: "Total Paid = Refund Amount + Forfeited Amount",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 360,
  },
  {
    setting_key: "cancellation.refund_amount",
    category: "Cancellation / Refund",
    label: "Refund Amount",
    formula_text: "Admin Input = Refund Amount",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 370,
  },
  {
    setting_key: "cancellation.forfeited_amount",
    category: "Cancellation / Refund",
    label: "Forfeited Amount",
    formula_text: "Total Paid - Refund Amount = Forfeited Amount",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 380,
  },
  {
    setting_key: "cancellation.clear_for_resale",
    category: "Cancellation / Refund",
    label: "Clear for Resale Rule",
    formula_text: "Cancellation Result + Settlement Date + Approved By + Refund/Forfeited Amount must exist before listing can return to Available",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 390,
  },
  {
    setting_key: "reports.total_sales",
    category: "Reports",
    label: "Total Sales",
    formula_text: "Sum of Total Contract Price from non-cancelled buyer accounts",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 400,
  },
  {
    setting_key: "reports.total_collections",
    category: "Reports",
    label: "Total Collections",
    formula_text: "Sum of verified payments",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 410,
  },
  {
    setting_key: "reports.outstanding_balance",
    category: "Reports",
    label: "Outstanding Balance",
    formula_text: "Total Contract Price - Verified Payments Applied",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 420,
  },
  {
    setting_key: "reports.commission_released",
    category: "Reports",
    label: "Commission Released",
    formula_text: "Sum of released commission release net amounts",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 430,
  },
  {
    setting_key: "reports.commission_payable",
    category: "Reports",
    label: "Commission Payable",
    formula_text: "Eligible Commission Releases - Released Commission Releases",
    description: null,
    value_type: "text",
    setting_value: null,
    default_value: null,
    is_editable: false,
    sort_order: 440,
  },
];

export const formulaSettingValueTypes = [
  "number",
  "percentage",
  "currency",
  "days",
  "text",
  "boolean",
  "json",
];

export const validateFormulaSettingValue = (valueType, value) => {
  const stringValue = value === null || value === undefined ? "" : String(value).trim();

  if (!formulaSettingValueTypes.includes(valueType)) {
    return {
      isValid: false,
      message: "Unknown formula setting value type.",
    };
  }

  if (valueType === "text") {
    if (stringValue.length > 1000) {
      return {
        isValid: false,
        message: "Text value must be 1000 characters or fewer.",
      };
    }

    return { isValid: true, normalizedValue: stringValue };
  }

  if (valueType === "json") {
    try {
      const parsedValue = JSON.parse(stringValue);
      return {
        isValid: true,
        normalizedValue: JSON.stringify(parsedValue),
      };
    } catch {
      return {
        isValid: false,
        message: "Value must be valid JSON.",
      };
    }
  }

  if (valueType === "boolean") {
    const normalizedValue = stringValue.toLowerCase();
    if (["true", "1", "yes"].includes(normalizedValue)) {
      return { isValid: true, normalizedValue: "true" };
    }
    if (["false", "0", "no"].includes(normalizedValue)) {
      return { isValid: true, normalizedValue: "false" };
    }

    return {
      isValid: false,
      message: "Value must be true or false.",
    };
  }

  const parsedValue = Number(stringValue);

  if (!Number.isFinite(parsedValue)) {
    return {
      isValid: false,
      message: "Value must be a valid number.",
    };
  }

  if (parsedValue < 0) {
    return {
      isValid: false,
      message: "Value cannot be negative.",
    };
  }

  if (valueType === "percentage" && parsedValue > 100) {
    return {
      isValid: false,
      message: "Percentage cannot exceed 100.",
    };
  }

  if (valueType === "days" && !Number.isInteger(parsedValue)) {
    return {
      isValid: false,
      message: "Days must be a whole number.",
    };
  }

  return {
    isValid: true,
    normalizedValue: String(parsedValue),
  };
};
